version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: sleep-stories-ollama
    ports:
      - "11434:11434"
    volumes:
      - sleepai_volume:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_MAX_LOADED_MODELS=1  # Optimized for RTX 3070Ti
    restart: unless-stopped
    networks:
      - sleep-stories-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build: ./backend
    container_name: sleep-stories-api
    ports:
      - "8000:8000"
    volumes:
      - sleepai_volume:/app/data
      - ./backend/logs:/app/logs  # Mount logs for debugging
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      - OLLAMA_URL=http://ollama:11434
      - DATA_PATH=/app/data
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
      # Enhanced configuration
      - SENSORY_ROTATION_ENABLED=true
      - SLEEP_TAPER_ENABLED=true
      - BEAT_PLANNING_ENABLED=true
      - MAX_CONCURRENT_MODELS=1  # RTX 3070Ti optimization
      - MAX_RETRIES=3
      - FALLBACK_MODEL=qwen2.5:7b
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        limits:
          memory: 16G  # Memory limit for stability
    restart: unless-stopped
    networks:
      - sleep-stories-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  ui:
    build: ./ui
    container_name: sleep-stories-ui-v2
    ports:
      - "7860:7860"
    volumes:
      - sleepai_volume:/app/data
      - ./ui/logs:/app/logs  # Mount logs for debugging
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - API_URL=http://backend:8000/api
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
      - DATA_PATH=/app/data
      - GRADIO_THEME=soft
      - GRADIO_ANALYTICS_ENABLED=false
      # Enhanced UI settings
      - UI_AUTO_REFRESH=true
      - UI_MAX_HISTORY=50
      - UI_STREAMING_ENABLED=true
    restart: unless-stopped
    networks:
      - sleep-stories-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  sleep-stories-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  sleepai_volume:
    external: true
